### ISSUE TITLE
6.0.19 is always missing

### ISSUE THREAD

**Issue by Neustradamus** [berkeleydb/libdb#7]
@gburd: The 6.0.19 is missing, can you update the source code?

It is the last one with Sleepycat licence.
- https://en.wikipedia.org/wiki/Sleepycat_License
- https://en.wikipedia.org/wiki/Berkeley_DB

Thanks in advance.

**Comment by Neustradamus** [comment]
Official source:
```
Changes between 12.1.6.0.19 and 12.1.6.0.20 Updated LICENSE file to reflect change to AGPL. [#22590]
```
- https://download.oracle.com/otndocs/products/berkeleydb/html/changelog_6_0.html#idp509784

It confirms that 6.0.19 has Sleepycat licence.

**Comment by Neustradamus** [comment]
Dear Oracle DB team members (part 1),

After to solve the issue about DB 5.3.28 problem, specified in the previous ticket, can you solve this ticket, DB 6.0.19 (12.1.6.0.19) is missing here.

Thanks in advance.

@krisrice
@JetterMcTedder
@bamcgill
@gvenzl
@bjeffrie
@moose56
@thatjeffsmith
@maxime-tremblay
@spavlusieva
@cdivilly
@brunoborges
@Snaugle
@loiclefevre
@Michael-A-McMahon
@jeandelavarene
@Kuassim
@AkshataMoon
@pat-goins
@sephiroth-j
@hbutani
@bengsig
@gamecube7561
@Djelibeybi
@0o001
@bharath-ramaprasad
@psaini79
@psaini2018
@kephir4eg
@s1saurabh
@jpverma85
@rathodsachin20
@alexkeh
@christianshay
@seesharper
@jjspiegel
@markddrake
@SrikrishnanS
@SrinivasKareenhalli
@VedantMahajanOracle
@knordin

**Comment by Neustradamus** [comment]
Dear Oracle DB team members (part 2),

After to solve the issue about DB 5.3.28 problem, specified in the previous ticket, can you solve this ticket, DB 6.0.19 (12.1.6.0.19) is missing here.

Thanks in advance.

@MiguelSilvaR
@morgiyan
@kzhou312
@aosingh
@sk192
@rkope99
@ThoSap
@younesAmin
@LesiaChaban
@algol68
@jbampton
@dataders
@alina-yur
@ting-lan-wang
@MouhsinElmajdouby
@fmeheust
@norah-li
@psilberk
@BidyadharM
@ayouballali
@anthony-tuininga
@cjbj
@markxnelson
@anders-swanson
@paulparkinson
@andytael
@gotsysdba
@neilschelly
@valrusu
@pasimoes
@4Aiur
@VictorErmakov
@rlagyu0

**Comment by gburd** [comment]
@Neustradamus please refrain from @-posting for more attention.  I don't want to ban people, but continuing to do that will force my hand.

I've addressed your concerns for 5.3.28 in another thread.  I'll re-consider newer releases when I have more time.  I hope to build a collaborative/vibrant/kind community around BDB over time.  I'd like you to be part of that, but only if you can participate in a way that fits within community standards.  Kind regards.

**Comment by Neustradamus** [comment]
@gburd: Thanks for your answer, never too late! :)

I would like a good community too, I am very happy to have seen the @dustinkirkland confirmation of my initial request.

Today, after more 5 years, you have solved these tickets:
- https://github.com/berkeleydb/libdb/issues/2
- https://github.com/berkeleydb/libdb/issues/8

Please keep this ticket opened, it has been not solved...

**Comment by gburd** [comment]
> Today, after more 5 years, you have solved these tickets:

This is an example of commentary that violates the community policies I set out for this project.

I'm closing this ticket because a) I can't find a copy of 6.0.19 and b) I plan on using my time to update the project either to the later versions of code released by Oracle (18+) or to fork it where it is an start development on much needed features in my (copious) spare time.

**Comment by Neustradamus** [comment]
@gburd: I am happy to see your changes about more recent versions.

It is very important to listen all people, I know that badly, originally, I am the only guy who has alerted you about the source.

It is important to have old to recent versions, to have a real history.

Recall, a long time ago, I have requested you more recent version here:
- https://github.com/berkeleydb/libdb/issues/5

**Comment by gburd** [comment]
Open source is about contributing time and effort.  Outside of these bug reports what have you contributed?On Apr 21, 2026, at 5:07 PM, Neustradamus ***@***.***> wrote:﻿Neustradamus left a comment (berkeleydb/libdb#7)
@gburd: I am happy to see your changes about more recent versions.
It is very important to listen all people, I know that badly, originally, I am the only guy who has alerted you about the source.
It is important to have old to recent versions, to have a real history.
Recall, a long time ago, I have requested you more recent version here:

#5

**Comment by Neustradamus** [comment]
@gburd: First, this organization has not up-to-date historical source code, so we can not work here.

So, I can publish a PR by libdn version?

**Comment by gburd** [comment]
Answering your question directly, belatedly — **yes, please do open a PR.** That offer went unanswered for months, which was my oversight, and my previous reply was sharper than warranted. Sorry.

Your stated blocker was that the historical source wasn't here to work against. That has largely been fixed since:

- **63 version tags** now exist, spanning `v1.85` through `v5.3.36`, including the 1.85 patch series, the 2.x/3.x/4.x lines, and the `.NC` no-crypto variants.
- `db 2.3.16` and `db 2.4.14` were added in #135/#156 after being recovered from the Debian source archive (Oracle no longer serves them) and verified as genuine Sleepycat releases by their embedded `DB_VERSION_STRING` and pinned SHA-256.
- The import tooling and provenance for every tarball is documented in `historical-import/SOURCES.md` on the `historical` branch, so the chain is reproducible rather than trust-me.

Known gaps, stated honestly: seven versions I could not locate anywhere (`2.5.9`, `2.6.4`, `4.1.24`, `4.4.16`, `6.0.35`, `18.1.25`, `18.1.32`) after checking Oracle, the Debian archive, archive.org's Wayback Machine, Software Heritage, Fedora's lookaside cache, Gentoo distfiles, and FreeBSD ports. Three more (`5.2.28`, `5.2.36`, `5.3.15`) are recoverable and on the list. Anything 6.0 or later is permanently out of scope because it is AGPLv3 — Oracle's own `license_change60.html` confirms it — and relicensing this fork isn't a decision I'll make for downstream users.

One scoping note so a PR doesn't get wasted effort: the `historical` branch is rebuilt by a script that replays the whole timeline and force-pushes, so changes there are best proposed as additions to `historical-import/` (the tarball manifest plus its provenance entry) rather than as commits on the branch itself. Work on `master` follows the normal PR flow.

If you want to add missing versions, a manifest entry with a verifiable source URL and checksum is the most useful contribution — that is exactly how #135 was resolved.

**Comment by Neustradamus** [comment]
@gburd: Some points:

About 6.0.19, I have found:
- https://www.google.com/search?q=Berkeley+DB+6.0.19
- https://sourceforge.net/p/gnucobol/discussion/help/thread/ba81633b59/
- https://oss.oracle.com/pipermail/bdb/2013-June/000056.html
- 6.0.19 direct link: http://download.oracle.com/berkeley-db/db-6.0.19.tar.gz

BLFS link:
- https://www.linuxfromscratch.org/blfs/view/7.6-systemd/server/db.html

About Oracle website with several informations:
- https://www.oracle.com/technetwork/jp/products/berkeleydb/downloads/index-090620-ja.html

Current Oracle link:
- https://www.oracle.com/database/technologies/related/berkeleydb-downloads.html

There are too:
- https://github.com/yasuhirokimura/db6
- https://github.com/yasuhirokimura/db18
- https://www.freshports.org/databases/db6

I have seen that libdb-5.3.28-42 exists:
- https://www.google.com/search?q=5.3.28-42

Can you update it?

Thanks in advance

**Comment by gburd** [comment]
I am working with Oracle asking for a license change from AGPLv3 to ASLv2, but that is not a certainty. If they choose to relicense BDB I'll bring in those additional historical versions.  New versions, new development is calver.org so as to be distinct going forward from the old semver.org tags/releases.  I'll look into those links, this isn't a formal support channel just a person doing some work in his spare time.
